TRACKER: "deep_sort"
SOURCE: "/media/zanella/mt/mp4/piazza_fiera_2.mp4"
OUTPUT: "inference/output"
EXP_ID: "4"
WEIGHTS: "yolov5/weights/yolov5x.pt"
IMAGE_SIZE: 800
CONF_THRES: 0.4
IOU-THRES: 0.5
FPS: 1
FOURCC: "mp4v"
DEVICE: "0"
VIEW_IMG: false
SAVE_TXT: true
CLASSES: [0]
AGNOSTIC-NMS: false
AUGMENT: false
DEEP_SORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
GT_FILE: "groundtruths/gt.txt"