TRACKER: "iou"
SOURCE: "/media/zanella/mt/mp4/"
OUTPUT: "inference/output"
EXP_ID: "1"
WEIGHTS: "yolov5/weights/yolov5l.pt"
IMAGE_SIZE: 640
CONF_THRES: 0.4
IOU-THRES: 0.5
FPS: 1
FOURCC: "mp4v"
DEVICE: "0"
VIEW_IMG: false
SAVE_TXT: true
CLASSES: [0]
AGNOSTIC-NMS: true
AUGMENT: true
IOU:
  MIN_CONFIDENCE: 0.3
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3