TRACKER: "iou"
SOURCE: "/media/zanella/mt/mp4/piazza_fiera_2.mp4"
OUTPUT: "inference/output"
EXP_ID: "5"
WEIGHTS: "yolov5/weights/yolov5x.pt"
IMAGE_SIZE: 800
CONF_THRES: 0.4
IOU-THRES: 0.5
FPS: 1
FOURCC: "mp4v"
DEVICE: "0"
VIEW_IMG: false
SAVE_TXT: true
CLASSES: [0]
AGNOSTIC-NMS: false
AUGMENT: false
IOU:
  MIN_CONFIDENCE: 0.3
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
GT_FILE: "groundtruths/gt.txt"